import { IRecipe } from 'typescript/interfaces/IRecipe';

export const MockRecipeList: IRecipe[] = [
	{
		vegetarian: true,
		vegan: false,
		glutenFree: false,
		dairyFree: false,
		veryHealthy: false,
		cheap: false,
		veryPopular: false,
		sustainable: false,
		lowFodmap: false,
		weightWatcherSmartPoints: 11,
		gaps: 'no',
		preparationMinutes: -1,
		cookingMinutes: -1,
		aggregateLikes: 7,
		healthScore: 1,
		creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
		license: 'CC BY 3.0',
		sourceName: 'Foodista',
		pricePerServing: 73.25,
		extendedIngredients: [
			{
				id: 1123,
				aisle: 'Milk, Eggs, Other Dairy',
				image: 'egg.png',
				consistency: 'SOLID',
				name: 'eggs',
				nameClean: 'egg',
				original: '3 Eggs',
				originalName: 'Eggs',
				amount: 3,
				unit: '',
				meta: [],
				measures: {
					us: {
						amount: 3,
						unitShort: '',
						unitLong: '',
					},
					metric: {
						amount: 3,
						unitShort: '',
						unitLong: '',
					},
				},
			},
			{
				id: 19335,
				aisle: 'Baking',
				image: 'sugar-in-bowl.png',
				consistency: 'SOLID',
				name: 'sugar',
				nameClean: 'sugar',
				original: '130g Sugar',
				originalName: 'Sugar',
				amount: 130,
				unit: 'g',
				meta: [],
				measures: {
					us: {
						amount: 4.586,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 130,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
			{
				id: 1001,
				aisle: 'Milk, Eggs, Other Dairy',
				image: 'butter-sliced.jpg',
				consistency: 'SOLID',
				name: 'butter',
				nameClean: 'butter',
				original: '75g Butter, softened',
				originalName: 'Butter, softened',
				amount: 75,
				unit: 'g',
				meta: ['softened'],
				measures: {
					us: {
						amount: 2.646,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 75,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
			{
				id: 12108,
				aisle: 'Baking',
				image: 'shredded-coconut.jpg',
				consistency: 'SOLID',
				name: 'desiccated coconut',
				nameClean: 'unsweetened coconut',
				original: '60g Desiccated coconut',
				originalName: 'Desiccated coconut',
				amount: 60,
				unit: 'g',
				meta: [],
				measures: {
					us: {
						amount: 2.116,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 60,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
			{
				id: 9156,
				aisle: 'Produce',
				image: 'zest-lemon.jpg',
				consistency: 'SOLID',
				name: 'lemon zest',
				nameClean: 'lemon peel',
				original: '11/2 tbsp Lemon zest',
				originalName: 'Lemon zest',
				amount: 5.5,
				unit: 'tbsp',
				meta: [],
				measures: {
					us: {
						amount: 5.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
					metric: {
						amount: 5.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
				},
			},
			{
				id: 9216,
				aisle: 'Produce',
				image: 'orange-zest.png',
				consistency: 'SOLID',
				name: 'orange zest',
				nameClean: 'orange zest',
				original: '1 1/2 tbsp Orange zest',
				originalName: 'Orange zest',
				amount: 1.5,
				unit: 'tbsp',
				meta: [],
				measures: {
					us: {
						amount: 1.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
					metric: {
						amount: 1.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
				},
			},
			{
				id: 9152,
				aisle: 'Produce',
				image: 'lemon-juice.jpg',
				consistency: 'LIQUID',
				name: 'lemon juice',
				nameClean: 'lemon juice',
				original: '60ml Lemon juice (or add to taste)',
				originalName: 'Lemon juice (or add to taste)',
				amount: 60,
				unit: 'ml',
				meta: ['to taste', '(or add )'],
				measures: {
					us: {
						amount: 2.029,
						unitShort: 'fl. oz',
						unitLong: 'fl. ozs',
					},
					metric: {
						amount: 60,
						unitShort: 'ml',
						unitLong: 'milliliters',
					},
				},
			},
			{
				id: 9206,
				aisle: 'Beverages',
				image: 'orange-juice.jpg',
				consistency: 'LIQUID',
				name: 'orange juice',
				nameClean: 'orange juice',
				original: '125m Orange juice',
				originalName: '125m Orange juice',
				amount: 1,
				unit: 'serving',
				meta: [],
				measures: {
					us: {
						amount: 1,
						unitShort: 'serving',
						unitLong: 'serving',
					},
					metric: {
						amount: 1,
						unitShort: 'serving',
						unitLong: 'serving',
					},
				},
			},
			{
				id: 12118,
				aisle: 'Canned and Jarred;Milk, Eggs, Other Dairy',
				image: 'coconut-milk.png',
				consistency: 'LIQUID',
				name: 'coconut milk',
				nameClean: 'coconut milk',
				original: '200ml Thick coconut milk',
				originalName: 'Thick coconut milk',
				amount: 200,
				unit: 'ml',
				meta: ['thick'],
				measures: {
					us: {
						amount: 6.764,
						unitShort: 'fl. oz',
						unitLong: 'fl. ozs',
					},
					metric: {
						amount: 200,
						unitShort: 'ml',
						unitLong: 'milliliters',
					},
				},
			},
			{
				id: 20081,
				aisle: 'Baking',
				image: 'flour.png',
				consistency: 'SOLID',
				name: 'plain flour',
				nameClean: 'wheat flour',
				original: '70g Plain flour, sifted',
				originalName: 'Plain flour, sifted',
				amount: 70,
				unit: 'g',
				meta: ['plain', 'sifted'],
				measures: {
					us: {
						amount: 2.469,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 70,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
		],
		id: 631785,
		title: 'Impossible" Coconut Pie',
		readyInMinutes: 45,
		servings: 10,
		sourceUrl:
			'https://www.foodista.com/recipe/CBTKCKX4/impossible-coconut-pie',
		image: 'https://spoonacular.com/recipeImages/631785-556x370.jpg',
		imageType: 'jpg',
		summary:
			'Impossible" Coconut Pie could be just the <b>lacto ovo vegetarian</b> recipe you\'ve been looking for. This recipe serves 10 and costs 73 cents per serving. One serving contains <b>239 calories</b>, <b>3g of protein</b>, and <b>16g of fat</b>. 7 people were glad they tried this recipe. Not a lot of people really liked this dessert. A mixture of coconut milk, sugar, flour, and a handful of other ingredients are all it takes to make this recipe so delicious. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns a <b>rather bad spoonacular score of 15%</b>. Similar recipes are <a href="https://spoonacular.com/recipes/impossible-coconut-pie-560495">Impossible Coconut Pie</a>, <a href="https://spoonacular.com/recipes/impossible-pie-327867">Impossible Pie</a>, and <a href="https://spoonacular.com/recipes/impossible-pie-69737">Impossible Pie</a>.',
		cuisines: [],
		dishTypes: ['dessert'],
		diets: ['lacto ovo vegetarian'],
		occasions: [],
		instructions:
			'Preheat oven to 170C.\nPlace the eggs, sugar, butter, desiccated coconut, lemon and orange zest and juice, coconut milk and flour in a food processor and blend until well combined. Pour into a buttered 22cm (9 inch) pie tray.\nPlace pie tray at the lower rack of the oven and bake for 60 - 80 minutes. Loosely cover with aluminium foil when you find the pie turning brown during half way of baking.  Set aside to cool, then refrigerate for 1 hour to chill.\nSlice and serve with a little whipped cream and passionfruit or  blueberry jam and sprinkle some toasted desiccated coconut over it.',
		analyzedInstructions: [
			{
				name: '',
				steps: [
					{
						number: 1,
						step: 'Preheat oven to 170C.',
						ingredients: [],
						equipment: [
							{
								id: 404784,
								name: 'oven',
								localizedName: 'oven',
								image: 'oven.jpg',
							},
						],
					},
					{
						number: 2,
						step: 'Place the eggs, sugar, butter, desiccated coconut, lemon and orange zest and juice, coconut milk and flour in a food processor and blend until well combined.',
						ingredients: [
							{
								id: 12108,
								name: 'desiccated coconut',
								localizedName: 'desiccated coconut',
								image: 'shredded-coconut.jpg',
							},
							{
								id: 12118,
								name: 'coconut milk',
								localizedName: 'coconut milk',
								image: 'coconut-milk.png',
							},
							{
								id: 9216,
								name: 'orange zest',
								localizedName: 'orange zest',
								image: 'orange-zest.png',
							},
							{
								id: 1001,
								name: 'butter',
								localizedName: 'butter',
								image: 'butter-sliced.jpg',
							},
							{
								id: 20081,
								name: 'all purpose flour',
								localizedName: 'all purpose flour',
								image: 'flour.png',
							},
							{
								id: 1019016,
								name: 'juice',
								localizedName: 'juice',
								image: 'apple-juice.jpg',
							},
							{
								id: 9150,
								name: 'lemon',
								localizedName: 'lemon',
								image: 'lemon.png',
							},
							{
								id: 19335,
								name: 'sugar',
								localizedName: 'sugar',
								image: 'sugar-in-bowl.png',
							},
							{
								id: 1123,
								name: 'egg',
								localizedName: 'egg',
								image: 'egg.png',
							},
						],
						equipment: [
							{
								id: 404771,
								name: 'food processor',
								localizedName: 'food processor',
								image: 'food-processor.png',
							},
						],
					},
					{
						number: 3,
						step: 'Pour into a buttered 22cm (9 inch) pie tray.',
						ingredients: [],
						equipment: [],
					},
					{
						number: 4,
						step: 'Place pie tray at the lower rack of the oven and bake for 60 - 80 minutes. Loosely cover with aluminium foil when you find the pie turning brown during half way of baking.  Set aside to cool, then refrigerate for 1 hour to chill.',
						ingredients: [],
						equipment: [
							{
								id: 404765,
								name: 'aluminum foil',
								localizedName: 'aluminum foil',
								image: 'aluminum-foil.png',
							},
							{
								id: 404784,
								name: 'oven',
								localizedName: 'oven',
								image: 'oven.jpg',
							},
						],
					},
					{
						number: 5,
						step: 'Slice and serve with a little whipped cream and passionfruit or  blueberry jam and sprinkle some toasted desiccated coconut over it.',
						ingredients: [
							{
								id: 12108,
								name: 'desiccated coconut',
								localizedName: 'desiccated coconut',
								image: 'shredded-coconut.jpg',
							},
							{
								id: 11119297,
								name: 'blueberry jam',
								localizedName: 'blueberry jam',
								image: 'blueberry-jam.jpg',
							},
							{
								id: 1054,
								name: 'whipped cream',
								localizedName: 'whipped cream',
								image: 'whipped-cream.jpg',
							},
							{
								id: 9231,
								name: 'passion fruit',
								localizedName: 'passion fruit',
								image: 'passion-fruit',
							},
						],
						equipment: [],
					},
				],
			},
		],
		originalId: null,
		spoonacularSourceUrl:
			'https://spoonacular.com/impossible-coconut-pie-631785',
	},
	{
		vegetarian: true,
		vegan: false,
		glutenFree: false,
		dairyFree: false,
		veryHealthy: false,
		cheap: false,
		veryPopular: false,
		sustainable: false,
		lowFodmap: false,
		weightWatcherSmartPoints: 11,
		gaps: 'no',
		preparationMinutes: -1,
		cookingMinutes: -1,
		aggregateLikes: 7,
		healthScore: 1,
		creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
		license: 'CC BY 3.0',
		sourceName: 'Foodista',
		pricePerServing: 73.25,
		extendedIngredients: [
			{
				id: 1123,
				aisle: 'Milk, Eggs, Other Dairy',
				image: 'egg.png',
				consistency: 'SOLID',
				name: 'eggs',
				nameClean: 'egg',
				original: '3 Eggs',
				originalName: 'Eggs',
				amount: 3,
				unit: '',
				meta: [],
				measures: {
					us: {
						amount: 3,
						unitShort: '',
						unitLong: '',
					},
					metric: {
						amount: 3,
						unitShort: '',
						unitLong: '',
					},
				},
			},
			{
				id: 19335,
				aisle: 'Baking',
				image: 'sugar-in-bowl.png',
				consistency: 'SOLID',
				name: 'sugar',
				nameClean: 'sugar',
				original: '130g Sugar',
				originalName: 'Sugar',
				amount: 130,
				unit: 'g',
				meta: [],
				measures: {
					us: {
						amount: 4.586,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 130,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
			{
				id: 1001,
				aisle: 'Milk, Eggs, Other Dairy',
				image: 'butter-sliced.jpg',
				consistency: 'SOLID',
				name: 'butter',
				nameClean: 'butter',
				original: '75g Butter, softened',
				originalName: 'Butter, softened',
				amount: 75,
				unit: 'g',
				meta: ['softened'],
				measures: {
					us: {
						amount: 2.646,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 75,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
			{
				id: 12108,
				aisle: 'Baking',
				image: 'shredded-coconut.jpg',
				consistency: 'SOLID',
				name: 'desiccated coconut',
				nameClean: 'unsweetened coconut',
				original: '60g Desiccated coconut',
				originalName: 'Desiccated coconut',
				amount: 60,
				unit: 'g',
				meta: [],
				measures: {
					us: {
						amount: 2.116,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 60,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
			{
				id: 9156,
				aisle: 'Produce',
				image: 'zest-lemon.jpg',
				consistency: 'SOLID',
				name: 'lemon zest',
				nameClean: 'lemon peel',
				original: '11/2 tbsp Lemon zest',
				originalName: 'Lemon zest',
				amount: 5.5,
				unit: 'tbsp',
				meta: [],
				measures: {
					us: {
						amount: 5.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
					metric: {
						amount: 5.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
				},
			},
			{
				id: 9216,
				aisle: 'Produce',
				image: 'orange-zest.png',
				consistency: 'SOLID',
				name: 'orange zest',
				nameClean: 'orange zest',
				original: '1 1/2 tbsp Orange zest',
				originalName: 'Orange zest',
				amount: 1.5,
				unit: 'tbsp',
				meta: [],
				measures: {
					us: {
						amount: 1.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
					metric: {
						amount: 1.5,
						unitShort: 'Tbsps',
						unitLong: 'Tbsps',
					},
				},
			},
			{
				id: 9152,
				aisle: 'Produce',
				image: 'lemon-juice.jpg',
				consistency: 'LIQUID',
				name: 'lemon juice',
				nameClean: 'lemon juice',
				original: '60ml Lemon juice (or add to taste)',
				originalName: 'Lemon juice (or add to taste)',
				amount: 60,
				unit: 'ml',
				meta: ['to taste', '(or add )'],
				measures: {
					us: {
						amount: 2.029,
						unitShort: 'fl. oz',
						unitLong: 'fl. ozs',
					},
					metric: {
						amount: 60,
						unitShort: 'ml',
						unitLong: 'milliliters',
					},
				},
			},
			{
				id: 9206,
				aisle: 'Beverages',
				image: 'orange-juice.jpg',
				consistency: 'LIQUID',
				name: 'orange juice',
				nameClean: 'orange juice',
				original: '125m Orange juice',
				originalName: '125m Orange juice',
				amount: 1,
				unit: 'serving',
				meta: [],
				measures: {
					us: {
						amount: 1,
						unitShort: 'serving',
						unitLong: 'serving',
					},
					metric: {
						amount: 1,
						unitShort: 'serving',
						unitLong: 'serving',
					},
				},
			},
			{
				id: 12118,
				aisle: 'Canned and Jarred;Milk, Eggs, Other Dairy',
				image: 'coconut-milk.png',
				consistency: 'LIQUID',
				name: 'coconut milk',
				nameClean: 'coconut milk',
				original: '200ml Thick coconut milk',
				originalName: 'Thick coconut milk',
				amount: 200,
				unit: 'ml',
				meta: ['thick'],
				measures: {
					us: {
						amount: 6.764,
						unitShort: 'fl. oz',
						unitLong: 'fl. ozs',
					},
					metric: {
						amount: 200,
						unitShort: 'ml',
						unitLong: 'milliliters',
					},
				},
			},
			{
				id: 20081,
				aisle: 'Baking',
				image: 'flour.png',
				consistency: 'SOLID',
				name: 'plain flour',
				nameClean: 'wheat flour',
				original: '70g Plain flour, sifted',
				originalName: 'Plain flour, sifted',
				amount: 70,
				unit: 'g',
				meta: ['plain', 'sifted'],
				measures: {
					us: {
						amount: 2.469,
						unitShort: 'oz',
						unitLong: 'ounces',
					},
					metric: {
						amount: 70,
						unitShort: 'g',
						unitLong: 'grams',
					},
				},
			},
		],
		id: 631785,
		title: 'Impossible" Coconut Pie',
		readyInMinutes: 45,
		servings: 10,
		sourceUrl:
			'https://www.foodista.com/recipe/CBTKCKX4/impossible-coconut-pie',
		image: 'https://spoonacular.com/recipeImages/631785-556x370.jpg',
		imageType: 'jpg',
		summary:
			'Impossible" Coconut Pie could be just the <b>lacto ovo vegetarian</b> recipe you\'ve been looking for. This recipe serves 10 and costs 73 cents per serving. One serving contains <b>239 calories</b>, <b>3g of protein</b>, and <b>16g of fat</b>. 7 people were glad they tried this recipe. Not a lot of people really liked this dessert. A mixture of coconut milk, sugar, flour, and a handful of other ingredients are all it takes to make this recipe so delicious. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns a <b>rather bad spoonacular score of 15%</b>. Similar recipes are <a href="https://spoonacular.com/recipes/impossible-coconut-pie-560495">Impossible Coconut Pie</a>, <a href="https://spoonacular.com/recipes/impossible-pie-327867">Impossible Pie</a>, and <a href="https://spoonacular.com/recipes/impossible-pie-69737">Impossible Pie</a>.',
		cuisines: [],
		dishTypes: ['dessert'],
		diets: ['lacto ovo vegetarian'],
		occasions: [],
		instructions:
			'Preheat oven to 170C.\nPlace the eggs, sugar, butter, desiccated coconut, lemon and orange zest and juice, coconut milk and flour in a food processor and blend until well combined. Pour into a buttered 22cm (9 inch) pie tray.\nPlace pie tray at the lower rack of the oven and bake for 60 - 80 minutes. Loosely cover with aluminium foil when you find the pie turning brown during half way of baking.  Set aside to cool, then refrigerate for 1 hour to chill.\nSlice and serve with a little whipped cream and passionfruit or  blueberry jam and sprinkle some toasted desiccated coconut over it.',
		analyzedInstructions: [
			{
				name: '',
				steps: [
					{
						number: 1,
						step: 'Preheat oven to 170C.',
						ingredients: [],
						equipment: [
							{
								id: 404784,
								name: 'oven',
								localizedName: 'oven',
								image: 'oven.jpg',
							},
						],
					},
					{
						number: 2,
						step: 'Place the eggs, sugar, butter, desiccated coconut, lemon and orange zest and juice, coconut milk and flour in a food processor and blend until well combined.',
						ingredients: [
							{
								id: 12108,
								name: 'desiccated coconut',
								localizedName: 'desiccated coconut',
								image: 'shredded-coconut.jpg',
							},
							{
								id: 12118,
								name: 'coconut milk',
								localizedName: 'coconut milk',
								image: 'coconut-milk.png',
							},
							{
								id: 9216,
								name: 'orange zest',
								localizedName: 'orange zest',
								image: 'orange-zest.png',
							},
							{
								id: 1001,
								name: 'butter',
								localizedName: 'butter',
								image: 'butter-sliced.jpg',
							},
							{
								id: 20081,
								name: 'all purpose flour',
								localizedName: 'all purpose flour',
								image: 'flour.png',
							},
							{
								id: 1019016,
								name: 'juice',
								localizedName: 'juice',
								image: 'apple-juice.jpg',
							},
							{
								id: 9150,
								name: 'lemon',
								localizedName: 'lemon',
								image: 'lemon.png',
							},
							{
								id: 19335,
								name: 'sugar',
								localizedName: 'sugar',
								image: 'sugar-in-bowl.png',
							},
							{
								id: 1123,
								name: 'egg',
								localizedName: 'egg',
								image: 'egg.png',
							},
						],
						equipment: [
							{
								id: 404771,
								name: 'food processor',
								localizedName: 'food processor',
								image: 'food-processor.png',
							},
						],
					},
					{
						number: 3,
						step: 'Pour into a buttered 22cm (9 inch) pie tray.',
						ingredients: [],
						equipment: [],
					},
					{
						number: 4,
						step: 'Place pie tray at the lower rack of the oven and bake for 60 - 80 minutes. Loosely cover with aluminium foil when you find the pie turning brown during half way of baking.  Set aside to cool, then refrigerate for 1 hour to chill.',
						ingredients: [],
						equipment: [
							{
								id: 404765,
								name: 'aluminum foil',
								localizedName: 'aluminum foil',
								image: 'aluminum-foil.png',
							},
							{
								id: 404784,
								name: 'oven',
								localizedName: 'oven',
								image: 'oven.jpg',
							},
						],
					},
					{
						number: 5,
						step: 'Slice and serve with a little whipped cream and passionfruit or  blueberry jam and sprinkle some toasted desiccated coconut over it.',
						ingredients: [
							{
								id: 12108,
								name: 'desiccated coconut',
								localizedName: 'desiccated coconut',
								image: 'shredded-coconut.jpg',
							},
							{
								id: 11119297,
								name: 'blueberry jam',
								localizedName: 'blueberry jam',
								image: 'blueberry-jam.jpg',
							},
							{
								id: 1054,
								name: 'whipped cream',
								localizedName: 'whipped cream',
								image: 'whipped-cream.jpg',
							},
							{
								id: 9231,
								name: 'passion fruit',
								localizedName: 'passion fruit',
								image: 'passion-fruit',
							},
						],
						equipment: [],
					},
				],
			},
		],
		originalId: null,
		spoonacularSourceUrl:
			'https://spoonacular.com/impossible-coconut-pie-631785',
	},
];
