name: CI
on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm ci
        cache:
          directories:
            - '$HOME/.npm'

      - name: Run Linter
        run: npm run lint
