name: CI
on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}-lint
          restore-keys: npm-

      - name: Install Packages
        run: npm ci

      - name: Run Linter
        run: npm run lint
