name: CI
on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm ci

      - name: Run Linter
        run: npm run lint

  testing:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm ci

      - name: Run Testing
        run: npm run test
